# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 11efec6e636155a27973f1f68a890028de177568669a8b9605e7020656dfe9675a14a1c5718383be70dceec3a112c9d1e3299e69b782d10d562ada36ad650de7

test:
  domain_name: example.com 
  secret_key_base: 88d8a8af46723ee9116abcf8d6046097321831d431c659a32c1e6cfac6c37021cd2b6e59c461449a6a9c555dab3b4e794795f6a6f5c8f895a9fdb36a7eeaae57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
